# Generated by Django 2.1.7 on 2019-03-19 10:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.UUIDField(default=uuid.uuid4, verbose_name='invoice id')),
                ('invoice_date', models.DateTimeField(default=datetime.datetime.now)),
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appstore.Order', verbose_name='Order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(default=datetime.datetime.now)),
                ('payment_amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appstore.Order', verbose_name='order'),
        ),
    ]
