# Generated by Django 2.1.5 on 2019-04-03 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
