# Generated by Django 2.1.7 on 2019-03-25 09:52

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0002_auto_20190319_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='image/default.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[500, 500], upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='category/default.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[500, 500], upload_to='Category/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='subcategory/default.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[1600, 500], upload_to='Subcategory/'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
