# Generated by Django 2.1.5 on 2019-04-20 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0002_auto_20190418_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='appstore.Address'),
        ),
    ]
