# Generated by Django 2.1.5 on 2019-04-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0003_auto_20190326_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
