# Generated by Django 2.1.7 on 2019-03-25 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0003_auto_20190325_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='image',
        ),
    ]
