# Generated by Django 2.1.7 on 2019-03-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0003_auto_20190309_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=500, null=True, verbose_name='About'),
        ),
    ]
