# Generated by Django 2.1.7 on 2019-03-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0004_remove_subcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=35, verbose_name='Name'),
        ),
    ]
