# Generated by Django 2.1.5 on 2019-04-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0005_auto_20190402_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
