# Generated by Django 2.1.7 on 2019-03-25 12:03

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0006_auto_20190325_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='image/default.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[800, 800], upload_to='image/'),
        ),
    ]
